language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
addons:
  postgresql: "9.3"
before_script:
  - mysql -e 'create database ah_bookshelf_plugin_test;'
  - psql  -c 'create database ah_bookshelf_plugin_test;' -U postgres